<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-OFU0FE0K" failures="1" tests="11" name="Default test" time="54.073" errors="0" timestamp="2025-09-07T18:32:01 IST">
  <testcase classname="tests.LoginTest" name="verifyCorrectUrlOpened" time="0.015"/>
  <testcase classname="tests.LoginTest" name="verifyLogin" time="9.397"/>
  <testcase classname="tests.LoginTest" name="verifyProductAddAndQuantity" time="10.391">
    <failure type="java.lang.AssertionError" message="Quantity did not increase! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Quantity did not increase! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.LoginTest.verifyProductAddAndQuantity(LoginTest.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyProductAddAndQuantity -->
  <testcase classname="tests.LoginTest" name="verifyCartClosedAndOrdersVisible" time="0.0">
    <skipped/>
  </testcase> <!-- verifyCartClosedAndOrdersVisible -->
  <testcase classname="tests.LoginTest" name="verifyAddiPhone12Pro" time="0.0">
    <skipped/>
  </testcase> <!-- verifyAddiPhone12Pro -->
  <testcase classname="tests.LoginTest" name="verifyCheckout" time="3.139"/>
  <testcase classname="tests.LoginTest" name="verifyAddressPositive" time="3.685"/>
  <testcase classname="tests.LoginTest" name="verifyReceiptAndContinue" time="3.286"/>
  <testcase classname="tests.LoginTest" name="seeorder" time="3.16"/>
  <testcase classname="tests.LoginTest" name="verifyAddToFavourites" time="0.447"/>
  <testcase classname="tests.LoginTest" name="verifyLogout" time="3.146"/>
</testsuite> <!-- Default test -->
